apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rznnslt9y-go
  janus-idp.io/tekton: rznnslt9y-go
  backstage.io/kubernetes-id: rznnslt9y-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rznnslt9y-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
